(define (left-subtree node) (car node))
(define (right-subtree node) (caddr node))
(define (value-of-tree node)(cadr node))

(define (collect-leaves-of-btree node)
	(if (null? node)
		'()
		(if (and (null? (right-subtree node)) (null? (left-subtree node)))
			(list (value-of-tree node))
			(if (null? (right-subtree node))
				(collect-leaves-of-btree (left-subtree node))
				(if (null? (left-subtree node))
					(collect-leaves-of-btree (right-subtree node))
					(append (collect-leaves-of-btree (left-subtree node)) (collect-leaves-of-btree (right-subtree node)))
				)
			)
		)
	  	
	))
